description: Opens a website in a headless browser and profiles its performance.
network: true

args:
  - name: url
    description: URL to open.
    required: true
  
  - name: screenshot
    description: Save a screenshot of the page.
    required: false
    artifact: true


  - name: wait-for
    description: CSS selector to wait for before profiling.
    required: false

  - name: wait-for-timeout
    description: Timeout in seconds for page load and element wait.
    required: false

  - name: performance-log
    description: Enable advanced performance logging.
    required: false
