description: Opens a website in a headless browser and profiles its performance.
network: true

args:
  - name: url
    description: URL to open.
    required: true
  - name: wait-for
    description: CSS selector to wait for before profiling.
    required: false
  - name: wait-for-timeout
    description: Timeout in seconds for page load and element wait.
    required: false
