description: Loads and profiles Python pickle files.
gpu: true

build_args:
  extra-requirements: EXTRA_REQUIREMENTS

args:
  - name: pickle
    description: Path to the python pickle file to deserialize.
    required: true
    volume: true

examples:
  - description: "Load a Pickle file:"
    command: dyana trace --loader pickle --pickle /path/to/file.pickle

  - description: "Networking is disabled by default, if you need to allow it, you can pass the --allow-network flag:"
    command: dyana trace --loader pickle --pickle /path/to/file.pickle --allow-network

  - description: "For pickles with special dependencies like torchvision models:"
    command: dyana trace --loader pickle --pickle /path/to/cifar_resnet.pkl --extra-requirements "torchvision"
