description: Loads and profiles Python pickle files.
gpu: true

build_args:
  extra-requirements: EXTRA_REQUIREMENTS

args:
  - name: pickle
    description: Path to the file to unpickle.
    required: true
    volume: true

examples:
  - description: "Load a pickle file:"
    command: dyana trace --loader pickle --pickle /path/to/file.pkl

  - description: "For pickles with special dependencies like torchvision models:"
    command: dyana trace --loader pickle --pickle /path/to/cifar_resnet.pkl --extra-requirements "torchvision"
